name: Cleanup Candles

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: "0 2 * * 0"
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cleanup old candles
        env:
          GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}
          GIST_ID: ${{ vars.VITE_GIST_ID }}
        run: |
          node -e "
          const GIST_ID = process.env.GIST_ID;
          const TOKEN = process.env.GITHUB_TOKEN;

          (async () => {
            try {
              console.log('🕯️ Starting weekly candle cleanup...');
              
              const response = await fetch(\`https://api.github.com/gists/\${GIST_ID}\`, {
                method: 'PATCH',
                headers: {
                  'Authorization': \`token \${TOKEN}\`,
                  'Accept': 'application/vnd.github.v3+json',
                  'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                  files: {
                    'candles.json': {
                      content: '[]'
                    }
                  }
                })
              });
              
              if (response.ok) {
                console.log('✅ All candles cleared successfully');
                console.log('🕯️ Memorial reset for new week of remembrance');
              } else {
                const errorText = await response.text();
                console.error('❌ Failed to clear candles:', response.status, errorText);
              }
              
            } catch (error) {
              console.error('❌ Error during cleanup:', error.message);
            }
          })();
